### ISSUE TITLE
colorchooser sample 2Gig RAM and 90+ CPU

### ISSUE THREAD

**Issue by badk** [netopyr/reduxfx#12] opened 2016-11-25 12:23 UTC
Have you ever tried it out?
If you pull a slider it goes wild on RAM and CPU usage.

**Comment by netopyr** [comment] 2016-11-25 13:12
I have noticed that sometimes the sample runs into an endless loop. The slider jumps back and forth and CPU goes up. Is that what you are seeing?

**Comment by netopyr** [comment] 2016-11-27 08:14
I think I found the issue and provided a fix. At least I was not able to reproduce the issue anymore. Can you please confirm?

**Comment by badk** [comment] 2016-11-28 09:53
yeah, i can confirm that. It looks like its fixed :+1:

**Comment by netopyr** [comment] 2016-11-28 12:41
Great, I close the issue now. You can certainly reopen it anytime, if the bug reappears.

Thanks for the feedback!

**Closed as completed by netopyr** 2016-11-28 12:41 UTC
Labels: bug
